/**
 * SK_lang_tr.h
 * SmartKraft SynDimm - Turkish Language Pack (Türkçe)
 * Version: v1.2.0
 */

#ifndef SK_LANG_TR_H
#define SK_LANG_TR_H

const char LANG_TR_JSON[] PROGMEM = R"rawliteral({
  "lang_code": "tr",
  "lang_name": "Türkçe",
  
  "tabs": {
    "quick": "Hızlı Kontrol",
    "modes": "Modlar",
    "connection": "Bağlantı",
    "info": "Info"
  },
  
  "quick": {
    "theme": "Tema",
    "theme_dark": "Koyu",
    "theme_light": "Açık",
    "language": "Dil",
    "mode_config": "Mod Yapılandırması",
    "mode_selection": "Mod Seçimi",
    "connection_settings": "Bağlantı Ayarları",
    "device_settings": "Cihaz Ayarları",
    "wifi_settings": "WiFi Ayarları",
    "save_device_settings": "Cihaz Ayarlarını Kaydet",
    "settings_saved": "Cihaz ayarları başarıyla kaydedildi"
  },
  
  "tooltip": {
    "dimmer_info": "Encoder döndürerek Shelly Dimmer parlaklığını kontrol eder. Sağa artırır, sola azaltır.",
    "shutter_info": "Shelly panjur kontrolü. Sağa kapatır, sola açar. Cihaz kalibrasyonu gerektirir.",
    "safe_info": "Şifre korumalı mod. API çağrıları için encoder dizileri tanımlayın.",
    "theme_hint": "Tercih otomatik kaydedilir.",
    "language_title": "Diller Hakkında",
    "language_info": "Tüm arayüz metinleri seçilen dile çevrilir. Ayar otomatik kaydedilir ve sayfa yenilenince uygulanır.",
    "mode_selection_info": "SynDimm cihazının hangi modda çalışacağını seçin ve modu yapılandırın.",
    "device_settings_info": "Cihazınız için tema, dil ve ağ ayarlarını yapılandırın.",
    "wifi_settings_info": "Cihazınızı ağınıza bağlamak için birincil ve yedek WiFi ayarlarını yapılandırın. Access Point (AP) modu ile cihazın kendi ağını oluşturmasını da kontrol edebilirsiniz.",
    "version_info": "Firmware güncellemelerini kontrol edin.",
    "factory_reset_info": "Tüm ayarları fabrika varsayılanlarına sıfırlar. Bu işlem geri alınamaz."
  },
  
  "modes": {
    "active": "Aktif",
    "passive": "Pasif",
    "error": "Hata"
  },
  
  "dimmer": {
    "title": "DIMMER",
    "description": "Shelly Dimmer cihazınızı encoder ile kontrol edin. Parlaklık ayarlayın ve açma/kapama işlemlerini yönetin.",
    "ip_address": "IP ADRESİ",
    "status": "DURUM",
    "calibration": "KALİBRASYON",
    "action": "AKSİYON",
    "on": "Açık",
    "off": "Kapalı",
    "connect": "Bağlan",
    "disconnect": "Bağlantıyı Kes",
    "device_connection": "Cihaz Bağlantısı",
    "manual_ip": "Manuel IP Girişi",
    "scan_network": "Ağı Tara",
    "stop_scan": "Taramayı Durdur",
    "saved_devices": "Kayıtlı Cihazlar",
    "no_devices": "Henüz kayıtlı cihaz yok. Ağ taraması yapın veya manuel bağlanın.",
    "no_saved_devices": "Henüz kayıtlı cihaz yok. Ağ taraması yapın veya manuel bağlanın.",
    "connecting": "Bağlanılıyor...",
    "connected": "Dimmer bağlandı!",
    "connection_failed": "Bağlantı başarısız",
    "disconnected": "Bağlantı kesildi",
    "enter_ip": "Lütfen IP girin!",
    "invalid_ip": "Geçersiz IP!",
    "calibration_saved": "Kalibrasyon kaydedildi!",
    "calibration_failed": "Kalibrasyon kaydedilemedi",
    "remove": "Kaldır",
    "device_removed": "Cihaz kaldırıldı",
    "remove_failed": "Kaldırma başarısız",
    "unknown": "Bilinmeyen",
    "shelly_dimmer": "Shelly Dimmer",
    "shelly_dali": "Shelly DALI",
    "tasmota": "Tasmota"
  },
  
  "shutter": {
    "title": "SHUTTER",
    "description": "Shelly Shutter cihazınızı encoder ile kontrol edin. Perde ve panjur pozisyonlarını kolayca ayarlayın.",
    "ip_address": "IP ADRESİ",
    "status": "DURUM",
    "position": "POZİSYON",
    "encoder_step": "ENCODER STEP",
    "connected": "Bağlı",
    "not_connected": "Bağlı Değil",
    "device_connection": "Cihaz Bağlantısı",
    "manual_ip": "Manuel IP Girişi",
    "connect": "Bağlan",
    "disconnect": "Bağlantıyı Kes",
    "scan_network": "Ağı Tara",
    "stop_scan": "Taramayı Durdur",
    "saved_devices": "Kayıtlı Cihazlar",
    "no_devices": "Henüz kayıtlı cihaz yok. Ağ taraması yapın veya manuel bağlanın.",
    "no_saved_devices": "Henüz kayıtlı cihaz yok. Ağ taraması yapın veya manuel bağlanın.",
    "connecting": "Bağlanılıyor...",
    "shutter_connected": "Shutter bağlandı!",
    "connection_failed": "Bağlantı başarısız",
    "disconnected": "Bağlantı kesildi",
    "info_text": "Shutter encoder ile kontrol edilir. Tarayıcınızdan sadece hız kalibrasyonu yapabilirsiniz. Teorik olarak tamamlanmış ancak gerçek panjur üzerinde test edilmemiştir.",
    "calibration_warning": "Shutter aygıtınız kalibre edilmediği için encoder dönüşü geçici olarak devre dışı. Ancak encoder butonu ile tam açma, kapama ve durdurma yapabilirsiniz.",
    "warning_encoder": "Shutter encoder ile kontrol edilir. Tarayıcınızdan sadece hız kalibrasyonu yapabilirsiniz. Teorik olarak tamamlanmış ancak gerçek dünyada panjur üzerinde test işlemi gerçekleştirilmemiştir.",
    "warning_calibration": "Shutter aygıtınız kalibre edilmediği için encoder dönüş hareketleri geçici olarak devre dışı. Ancak yine de encoder butonu ile tam açma, tam kapatma ve durdurma işlemlerini gerçekleştirmeye devam edebilirsiniz."
  },
  
  "safe": {
    "title": "SAFE",
    "description": "Encoder hareketleriyle şifre girişi yapılır. Her şifre için API endpoint tanımlayabilirsiniz. Doğru şifre girildiğinde ESP32C6 otomatik olarak tanımlı API'yi tetikler.",
    "password_1": "Şifre 1",
    "password_2": "Şifre 2",
    "password_3": "Şifre 3",
    "password_4": "Şifre 4",
    "password_5": "Şifre 5",
    "password_tab": "Şifre",
    "enable_password": "Şifreyi Etkinleştir",
    "password_label": "Şifre",
    "password": "Şifre",
    "password_format": "Format: L3-R12-L11-R3-B (Min: 3 adım, Max: 6 adım)",
    "api_url": "API URL",
    "custom_header": "Özel Header (opsiyonel)",
    "header_format": "Format: HeaderName: Value",
    "save_password": "Şifreyi Kaydet",
    "test_api": "API Test Et",
    "password_empty": "Şifre boş olamaz!",
    "invalid_format": "Geçersiz şifre formatı! Örnek: L3-R12-L11-R3-B",
    "api_empty": "API URL boş olamaz!",
    "saving": "Şifre kaydediliyor...",
    "saved": "Şifre başarıyla kaydedildi!",
    "save_failed": "Hata: Kaydedilemedi",
    "testing": "API test ediliyor...",
    "test_success": "API test başarılı! HTTP",
    "test_failed": "API test başarısız"
  },
  
  "alarm": {
    "title": "ALARM",
    "description": "Alarm modu, acil durumlarda sevdiklerinize anında haber vermek veya yardım istemek için tasarlanmış bir güvenlik özelliğidir. Encoder'la etkileşime girdiğinizde API üzerinden mobil uygulamaya sinyal gönderilir. Bu sinyal uygulamanın yüklü olduğu telefonların zil sesini tetikleyerek önceden belirlediğiniz mesajları ekranda gösterir.",
    "example_title": "Örnek Kullanım Senaryosu:",
    "example_text": "SynDimm cihazınız Alarm modundayken encoder ile herhangi bir etkileşime girdiğinizde, cihaz ID numaranızla bağlantı kurulmuş Android veya iOS cihazlardaki mobil uygulamasına otomatik olarak acil durum isteği gönderilir. Bildirim alan telefonlar yüksek sesle çalmaya başlar ve önceden belirlediğiniz acil durum mesajınız ekranda görüntülenir. Bu sayede, kişisel güvenliğiniz için bir panik butonu olarak kullanabileceğiniz akıllı bir çözüm sunar.",
    "dev_note": "Sistem şu anda geliştirme aşamasındadır ve yakında kullanıma sunulacaktır.",
    "note": "Not: Sistem şu anda geliştirme aşamasındadır ve yakında kullanıma sunulacaktır."
  },
  
  "connection": {
    "mode": "MOD",
    "ssid": "SSID",
    "ip_address": "IP ADRESİ",
    "ap_mode_title": "Access Point (AP) Mode",
    "ap_mode_info": "Cihaz ilk kurulumda otomatik olarak kendi ağını oluşturur. WiFi bağlantısı yapılandırıldıktan sonra kapatmanız önerilir. WiFi olmadan kullanmak istiyorsanız açık bırakın. Aşağıdaki erişim bilgileri sabittir ve AP mod aktifken her zaman geçerlidir.",
    "ap_mode_description": "WiFi bağlantısı başarısız olursa cihaz kendi ağını oluşturur. Ayarlara erişmek için bu ağa bağlanın.",
    "ap_mode_auto": "Otomatik",
    "ap_info": "WiFi bağlantısı kurulamazsa cihaz otomatik olarak kendi erişim noktasını açar. Bu sayede her zaman cihaza erişebilir ve ayarlarını yapabilirsiniz.",
    "ap_mode_desc": "WiFi bağlantısı kurulamazsa cihaz otomatik olarak kendi erişim noktasını açar. Bu sayede her zaman cihaza erişebilir ve ayarlarını yapabilirsiniz.",
    "wifi_connection_summary": "Cihaz bağlanır: Primary WiFi → Backup WiFi → Access Point (AP) Mode",
    "ap_quick_title": "Access Point (AP) Mode - Acil Erişim",
    "ap_disabled_warning": "Uyarı: AP Mode kapalıyken ve WiFi erişilemezse cihaza erişilemez! Böyle bir durum yaşanırsa cihazınızın orta butonuna 20 saniye basılı tutarak fabrika ayarlarına dönmesini sağlayabilirsiniz. Bu durumda kurulumu en baştan başlatmanız gerekecektir.",
    "network_name": "Ağ Adı (SSID)",
    "password": "Şifre",
    "no_password": "Yok (Açık Ağ)",
    "ip_address_label": "IP Adresi",
    "mdns": "mDNS",
    "connection_order": "Bağlantı Sırası",
    "step_primary": "1. Primary WiFi",
    "step_backup": "2. Backup WiFi",
    "step_ap": "3. AP Mode",
    "primary_wifi": "PRIMARY WIFI",
    "backup_wifi": "BACKUP WIFI",
    "not_configured": "Yapılandırılmadı",
    "configured": "Yapılandırıldı",
    "connected": "Bağlı",
    "ssid_label": "SSID",
    "enter_ssid": "WiFi SSID girin",
    "password_optional": "Şifre",
    "leave_empty_open": "Açık ağ için boş bırakın",
    "open_network": "Açık ağ için boş bırakın",
    "static_ip": "Statik IP (opsiyonel)",
    "leave_empty_dhcp": "DHCP için boş bırakın",
    "dhcp_hint": "DHCP için boş bırakın",
    "local_domain": ".local Alan Adı (yapılandırma önerilir)",
    "mdns_domain": ".local Alan Adı (yapılandırma önerilir)",
    "mdns_example": "örn: dimm",
    "mdns_hint": "Ağda [isim].local olarak erişilebilir olacak. Birden fazla SynDimm cihazınız varsa her cihaza farklı bir isim ataması yapmalısınız. Aynı isimle birden fazla cihaz yapılandırırsanız ağ içinde tutarsızlık oluşacak ve sistem çalışmayacaktır.",
    "save_network": "Ağ Yapılandırmasını Kaydet",
    "saving": "Ayarlar kaydediliyor...",
    "saved": "Ayarlar kaydedildi! Yeniden başlatılıyor...",
    "save_failed": "Hata: Kaydedilemedi",
    "validation_ssid_long": "SSID max 32 karakter",
    "validation_password": "Şifre 8-63 karakter olmalı",
    "validation_ip": "Geçersiz Statik IP",
    "validation_mdns": "mDNS max 63 karakter",
    "validation_wifi_required": "En az bir WiFi ağı gerekli",
    "scan": "Tara",
    "scan_wifi": "WiFi Ağlarını Tara",
    "scanning": "Taranıyor...",
    "no_networks": "Ağ bulunamadı",
    "rescan": "Yeniden Tara",
    "wifi_open": "Açık",
    "wifi_secured": "Şifreli",
    "wifi_selected": "'{ssid}' seçildi"
  },
  
  "info": {
    "version_update": "Versiyon Güncelleme",
    "device_version": "Cihaz Sürümü:",
    "new_version": "Yeni Sürüm Mevcut!",
    "new_version_available": "Yeni Sürüm Mevcut!",
    "release_date": "Yayın Tarihi:",
    "no_release_notes": "Sürüm notları yok",
    "auto_update": "Otomatik Güncelleme",
    "auto_update_info": "Otomatik güncelleme açık olduğunda cihaz yeni sürümleri kontrol eder ve kendini günceller. Kapalı olduğunda sadece bildirim alırsınız.",
    "auto_update_desc": "Otomatik güncelleme açık olduğunda cihaz yeni sürümleri kontrol eder ve kendini günceller. Kapalı olduğunda sadece bildirim alırsınız.",
    "check_update": "Güncelleme Kontrol Et",
    "update_now": "Şimdi Güncelle",
    "downloading": "İndiriliyor...",
    "installing": "Yükleniyor...",
    "completed": "Tamamlandı!",
    "checking": "Güncelleme kontrol ediliyor...",
    "update_found": "Yeni sürüm bulundu!",
    "up_to_date": "Cihazınız güncel!",
    "update_starting": "Güncelleme başlatılıyor...",
    "update_success": "Güncelleme başarılı! Yeniden başlatılıyor...",
    "update_failed": "Hata: Güncelleme başarısız",
    "update_confirm": "Güncelleme sırasında cihaz yeniden başlatılacak. Devam?",
    "usage_guide": "Kullanım Kılavuzu",
    "user_guide": "Kullanım Kılavuzu",
    "dimmer_mode": "Dimmer Modu",
    "dimmer_desc": "Shelly Dimmer cihazları ile entegre çalışır. Encoder ile aydınlatma parlaklığını kontrol edebilirsiniz.",
    "dimmer_mode_title": "Dimmer Modu",
    "dimmer_mode_desc": "Shelly Dimmer cihazları ile entegre çalışır. Encoder ile aydınlatma parlaklığını kontrol edebilirsiniz.",
    "encoder_rotation": "Encoder Dönüşü:",
    "dimmer_rotation_desc": "Sağa çevirme parlaklık artırır, sola çevirme azaltır.",
    "encoder_rotation_dimmer": "Sağa çevirme parlaklık artırır, sola çevirme azaltır.",
    "encoder_button": "Encoder Butonu:",
    "dimmer_button_desc": "Tek basma ile cihazı açar/kapatır (toggle).",
    "encoder_button_dimmer": "Tek basma ile cihazı açar/kapatır (toggle).",
    "calibration": "Kalibrasyon:",
    "dimmer_calibration_desc": "Web arayüzünden 1-5 arası kalibrasyon değeri ayarlanabilir. Bu değer her encoder hareketi için değişecek parlaklık yüzdesini belirler.",
    "calibration_title": "Kalibrasyon:",
    "calibration_dimmer": "Web arayüzünden 1-5 arası kalibrasyon değeri ayarlanabilir. Bu değer her encoder hareketi için değişecek parlaklık yüzdesini belirler.",
    "device_connection": "Cihaz Bağlantısı:",
    "dimmer_connection_desc": "Ağ Tara butonu ile yerel ağdaki Shelly Dimmer cihazlarını bulun ve bağlanın.",
    "device_connection_title": "Cihaz Bağlantısı:",
    "device_connection_dimmer": "Ağ Tara butonu ile yerel ağdaki Shelly Dimmer cihazlarını bulun ve bağlanın.",
    "shutter_mode": "Shutter Modu",
    "shutter_desc": "Shelly 2.5 veya Shelly Plus 2PM gibi panjur/kepenk kontrolcü cihazlarla çalışır.",
    "shutter_mode_title": "Shutter Modu",
    "shutter_mode_desc": "Shelly 2.5 veya Shelly Plus 2PM gibi panjur/kepenk kontrolcü cihazlarla çalışır.",
    "shutter_rotation_desc": "Sağa çevirme panjuru kapatır (aşağı), sola çevirme açar (yukarı). Not: Cihaz kalibre edilmemişse encoder dönüşü devre dışı kalır.",
    "encoder_rotation_shutter": "Sağa çevirme panjuru kapatır (aşağı), sola çevirme açar (yukarı). Not: Cihaz kalibre edilmemişse encoder dönüşü devre dışı kalır.",
    "shutter_button_desc": "Hareket halindeyse durdurur. Duruyorsa son hareketin tersine tam açma veya tam kapatma yapar.",
    "encoder_button_shutter": "Hareket halindeyse durdurur. Duruyorsa son hareketin tersine tam açma veya tam kapatma yapar.",
    "shutter_calibration_desc": "Shelly cihazının kendi uygulamasından motor kalibrasyonu yapılmalıdır. Web arayüzünden encoder hassasiyeti (1-5) ayarlanabilir.",
    "calibration_shutter": "Shelly cihazının kendi uygulamasından motor kalibrasyonu yapılmalıdır. Web arayüzünden encoder hassasiyeti (1-5) ayarlanabilir.",
    "safe_mode": "Safe Modu",
    "safe_desc": "Encoder hareketleriyle şifre girilir ve doğru şifrede belirlenen API çağrılır.",
    "safe_mode_title": "Safe Modu",
    "safe_mode_desc": "Encoder hareketleriyle şifre girilir ve doğru şifrede belirlenen API çağrılır.",
    "password_format_title": "Şifre Formatı:",
    "safe_format_desc": "R5-L3-R2-B gibi hareketlerden oluşur. R=sağa, L=sola, rakam=tur sayısı, B=buton.",
    "password_format_desc": "R5-L3-R2-B gibi hareketlerden oluşur. R=sağa, L=sola, rakam=tur sayısı, B=buton.",
    "settings": "Ayarlama:",
    "safe_settings_desc": "Web arayüzünden 5 farklı şifre tanımlanabilir. Her şifre için HTTP GET veya POST API URL girilir.",
    "safe_setup": "Ayarlama:",
    "safe_setup_desc": "Web arayüzünden 5 farklı şifre tanımlanabilir. Her şifre için HTTP GET veya POST API URL girilir.",
    "usage": "Kullanım:",
    "safe_usage_desc": "Akıllı kilit açma, garaj kapısı kontrolü, özel otomasyon senaryoları için uygundur.",
    "safe_usage": "Kullanım:",
    "alarm_mode": "Alarm Modu (Geliştirme Aşamasında)",
    "alarm_mode_title": "Alarm Modu (Geliştirme Aşamasında)",
    "emergency_notification": "Acil Bildirim:",
    "alarm_notification_desc": "Encoder'a dokunduğunuzda veya çevirdiğinizde (yön/miktar önemsiz) API üzerinden mobil uygulamaya sinyal gönderir.",
    "alarm_emergency": "Acil Bildirim:",
    "alarm_emergency_desc": "Encoder'a dokunduğunuzda veya çevirdiğinizde (yön/miktar önemsiz) API üzerinden mobil uygulamaya sinyal gönderir.",
    "function": "İşlev:",
    "alarm_function_desc": "Hedef telefonda zil sesi tetiklenir ve acil durum mesajı iletilir.",
    "alarm_function": "İşlev:",
    "alarm_dev_note": "Alarm modu geliştirme aşamasındadır.",
    "alarm_note": "Alarm modu geliştirme aşamasındadır.",
    "general_features": "Genel Özellikler",
    "mode_switch": "Mod Değiştirme:",
    "mode_switch_desc": "Encoder butonuna 3 saniye basılı tutun. Önizleme moduna geçer, encoder çevirilerek mod seçilir, tekrar 3 saniye basılı tutarak onaylayın.",
    "mode_switching": "Mod Değiştirme:",
    "mode_switching_desc": "Encoder butonuna 3 saniye basılı tutun. Önizleme moduna geçer, encoder çevirilerek mod seçilir, tekrar 3 saniye butona basılı tutularak seçim onaylanır.",
    "wifi_connection": "WiFi Bağlantısı:",
    "wifi_desc": "Bağlantı sekmesinden SSID ve şifre girerek WiFi ağına bağlanın. DHCP veya statik IP seçenekleri mevcuttur. mDNS desteği ile tarayıcıdan dimm.local adresiyle de erişebilirsiniz.",
    "wifi_connection_desc": "Bağlantı sekmesinden SSID ve şifre girerek WiFi ağına bağlanın. DHCP veya statik IP seçenekleri mevcuttur. mDNS desteği ile tarayıcıdan dimm.local adresiyle de erişebilirsiniz.",
    "quick_menu": "Hızlı Menü:",
    "quick_menu_desc": "Sağ üst köşedeki durum çubuğundan aktif mod, WiFi durumu ve IP adresini görebilirsiniz. Tıklandığında detaylı sistem bilgisi paneli açılır.",
    "mode_memory": "Mod Hafızası:",
    "mode_memory_desc": "Seçilen mod flash belleğine kaydedilir ve cihaz yeniden başlatıldığında otomatik olarak son aktif mod ile çalışır.",
    "ota_update": "OTA Güncelleme:",
    "ota_desc": "Info sekmesinden GitHub üzerindeki yeni sürümler kontrol edilebilir. Güncelleme mevcut ise tek tıkla kablosuz yükleme yapılabilir.",
    "ota_update_desc": "Info sekmesinden GitHub üzerindeki yeni sürümler kontrol edilebilir. Güncelleme mevcut ise tek tıkla kablosuz yükleme yapılabilir.",
    "system_operations": "Sistem İşlemleri",
    "restart": "Restart",
    "factory_reset": "Factory Reset",
    "factory_reset_confirm": "Tüm ayarlar silinecek. Onaylamak için <strong>Evet</strong> yazın:",
    "factory_reset_placeholder": "Evet",
    "confirm": "Onayla",
    "cancel": "İptal",
    "factory_reset_validation": "Onay için \"Evet\" yazmanız gerekiyor!",
    "restarting": "Cihaz yeniden başlatılıyor...",
    "restart_success": "Cihaz yeniden başlatıldı. Sayfa 5 saniye sonra yenilenecek.",
    "factory_resetting": "Factory reset yapılıyor...",
    "factory_reset_success": "Factory reset tamamlandı. Cihaz yeniden başlatılıyor...",
    "support_docs": "Destek ve Dokümantasyon",
    "support_desc": "Detaylı kullanım kılavuzu, örnek senaryolar ve güncellemeler için:"
  },
  
  "notifications": {
    "connection_error": "Bağlantı hatası",
    "scanning": "Ağ taranıyor...",
    "scan_started": "Tarama başladı",
    "scan_stopped": "Tarama durduruldu",
    "scan_failed": "Tarama başlatılamadı",
    "scan_progress": "Taranıyor: {percent}% ({scanned}/{total}) - {count} cihaz",
    "scan_complete": "Tamamlandı! {count} cihaz bulundu",
    "scan_complete_none": "Tamamlandı - cihaz bulunamadı",
    "setting_saved": "Ayar kaydedildi",
    "setting_failed": "Kaydedilemedi",
    "confirm_disconnect": "Bağlantıyı kesmek istediğinize emin misiniz?",
    "confirm_remove": "Bu cihazı kaldırmak istediğinize emin misiniz?",
    "confirm_stop_scan": "Taramayı durdurmak istiyor musunuz?"
  },
  
  "common": {
    "save": "Kaydet",
    "cancel": "İptal",
    "confirm": "Onayla",
    "close": "Kapat",
    "loading": "Yükleniyor...",
    "error": "Hata",
    "success": "Başarılı",
    "warning": "Uyarı",
    "info": "Bilgi",
    "yes": "Evet",
    "no": "Hayır",
    "on": "Açık",
    "off": "Kapalı",
    "enabled": "Aktif",
    "disabled": "Pasif",
    "connect": "Bağlan",
    "disconnect": "Bağlantıyı Kes",
    "increase": "Artır",
    "decrease": "Azalt",
    "passive": "Pasif",
    "active": "Aktif",
    "automatic": "Otomatik",
    "not_configured": "Yapılandırılmadı",
    "note": "Not:"
  }
})rawliteral";

#endif // SK_LANG_TR_H
