/**
 * SK_lang_en.h
 * SmartKraft SynDimm - English Language Pack
 * Version: v1.2.0
 */

#ifndef SK_LANG_EN_H
#define SK_LANG_EN_H

const char LANG_EN_JSON[] PROGMEM = R"rawliteral({
  "lang_code": "en",
  "lang_name": "English",
  
  "tabs": {
    "quick": "Quick Control",
    "modes": "Modes",
    "connection": "Connection",
    "info": "Info"
  },
  
  "quick": {
    "theme": "Theme",
    "theme_dark": "Dark",
    "theme_light": "Light",
    "language": "Language",
    "mode_config": "Mode Configuration",
    "mode_selection": "Mode Selection",
    "connection_settings": "Connection Settings",
    "device_settings": "Device Settings",
    "wifi_settings": "WiFi Settings",
    "save_device_settings": "Save Device Settings",
    "settings_saved": "Device settings saved successfully"
  },
  
  "tooltip": {
    "dimmer_info": "Controls Shelly Dimmer brightness with encoder rotation. Right increases, left decreases brightness.",
    "shutter_info": "Controls Shelly roller shutters. Right closes, left opens. Requires device calibration.",
    "safe_info": "Password-protected mode. Define encoder sequences as passwords to trigger API calls.",
    "theme_hint": "Preference is saved automatically.",
    "language_title": "About Languages",
    "language_info": "All interface texts will be translated to the selected language. The setting is saved automatically and applied on page reload.",
    "mode_selection_info": "Select the operating mode for the encoder. Each mode offers different functionality.",
    "device_settings_info": "Configure theme, language and network settings for your device.",
    "wifi_settings_info": "Configure primary and backup WiFi settings to connect your device to the network. You can also control whether the device creates its own network via Access Point (AP) mode.",
    "version_info": "Check for firmware updates over the air (OTA).",
    "factory_reset_info": "Resets all settings to factory defaults. This action cannot be undone."
  },
  
  "modes": {
    "active": "Active",
    "passive": "Passive",
    "error": "Error"
  },
  
  "dimmer": {
    "title": "DIMMER",
    "description": "Control your Shelly Dimmer with the encoder. Adjust brightness and manage on/off operations.",
    "ip_address": "IP ADDRESS",
    "status": "STATUS",
    "calibration": "CALIBRATION",
    "action": "ACTION",
    "on": "On",
    "off": "Off",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "device_connection": "Device Connection",
    "manual_ip": "Manual IP Entry",
    "scan_network": "Scan Network",
    "stop_scan": "Stop Scan",
    "saved_devices": "Saved Devices",
    "no_devices": "No saved devices yet. Scan network or connect manually.",
    "no_saved_devices": "No saved devices. Scan the network or connect manually.",
    "connecting": "Connecting...",
    "connected": "Dimmer connected!",
    "connection_failed": "Connection failed",
    "disconnected": "Disconnected",
    "enter_ip": "Please enter IP!",
    "invalid_ip": "Invalid IP!",
    "calibration_saved": "Calibration saved!",
    "calibration_failed": "Calibration save failed",
    "remove": "Remove",
    "device_removed": "Device removed",
    "remove_failed": "Remove failed",
    "unknown": "Unknown",
    "shelly_dimmer": "Shelly Dimmer",
    "shelly_dali": "Shelly DALI",
    "tasmota": "Tasmota"
  },
  
  "shutter": {
    "title": "SHUTTER",
    "description": "Control your Shelly Shutter with the encoder. Easily adjust curtain and blind positions.",
    "ip_address": "IP ADDRESS",
    "status": "STATUS",
    "position": "POSITION",
    "encoder_step": "ENCODER STEP",
    "connected": "Connected",
    "not_connected": "Not Connected",
    "device_connection": "Device Connection",
    "manual_ip": "Manual IP Entry",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "scan_network": "Scan Network",
    "stop_scan": "Stop Scan",
    "saved_devices": "Saved Devices",
    "no_devices": "No saved devices yet. Scan network or connect manually.",
    "no_saved_devices": "No saved devices. Scan the network or connect manually.",
    "connecting": "Connecting...",
    "shutter_connected": "Shutter connected!",
    "connection_failed": "Connection failed",
    "disconnected": "Disconnected",
    "info_text": "Shutter is controlled by encoder. You can only calibrate speed from your browser. Theoretically complete but not tested on real shutter.",
    "calibration_warning": "Your shutter device is not calibrated, encoder rotation is temporarily disabled. However, you can still perform full open, full close and stop operations with the encoder button.",
    "warning_encoder": "Shutter is controlled via encoder. You can only adjust speed calibration from your browser. Theoretically complete but not tested on a real shutter in the real world.",
    "warning_calibration": "Your shutter device is not calibrated, so encoder rotation movements are temporarily disabled. However, you can still perform full open, full close and stop operations using the encoder button."
  },
  
  "safe": {
    "title": "SAFE",
    "description": "Password entry is done with encoder movements. You can define an API endpoint for each password. When the correct password is entered, ESP32C6 automatically triggers the defined API.",
    "password_1": "Password 1",
    "password_2": "Password 2",
    "password_3": "Password 3",
    "password_4": "Password 4",
    "password_5": "Password 5",
    "password_tab": "Password",
    "enable_password": "Enable Password",
    "password_label": "Password",
    "password": "Password",
    "password_format": "Format: L3-R12-L11-R3-B (Min: 3 steps, Max: 6 steps)",
    "api_url": "API URL",
    "custom_header": "Custom Header (optional)",
    "header_format": "Format: HeaderName: Value",
    "save_password": "Save Password",
    "test_api": "Test API",
    "password_empty": "Password cannot be empty!",
    "invalid_format": "Invalid password format! Example: L3-R12-L11-R3-B",
    "api_empty": "API URL cannot be empty!",
    "saving": "Saving password...",
    "saved": "Password saved successfully!",
    "save_failed": "Error: Could not save",
    "testing": "Testing API...",
    "test_success": "API test successful! HTTP",
    "test_failed": "API test failed"
  },
  
  "alarm": {
    "title": "ALARM",
    "description": "Alarm mode is a security feature designed to instantly notify your loved ones or request help in emergencies. When you interact with the encoder, a signal is sent to the mobile app via API. This signal triggers the ringtone of phones with the app installed and displays your predetermined messages on screen.",
    "example_title": "Example Usage Scenario:",
    "example_text": "When you interact with the encoder while your SynDimm device is in Alarm mode, an emergency request is automatically sent to the mobile app on Android or iOS devices linked with your device ID. Phones receiving the notification start ringing loudly and your predetermined emergency message is displayed on screen. This provides a smart solution you can use as a panic button for your personal safety.",
    "dev_note": "The system is currently under development and will be available soon.",
    "note": "Note: The system is currently under development and will be available soon."
  },
  
  "connection": {
    "mode": "MODE",
    "ssid": "SSID",
    "ip_address": "IP ADDRESS",
    "ap_mode_title": "Access Point (AP) Mode",
    "ap_mode_info": "The device automatically creates its own network during initial setup. It is recommended to disable this after WiFi is configured. Keep it enabled if you want to use without WiFi. The access credentials below are fixed and always valid when AP mode is active.",
    "ap_mode_description": "If WiFi connection fails, the device creates its own network. Connect to this network to access settings.",
    "ap_mode_auto": "Automatic",
    "ap_info": "If WiFi connection cannot be established, the device automatically opens its own access point. This way you can always access the device and configure its settings.",
    "ap_mode_desc": "If WiFi connection cannot be established, the device automatically opens its own access point. This way you can always access and configure the device.",
    "wifi_connection_summary": "Device connects: Primary WiFi → Backup WiFi → Access Point (AP) Mode",
    "ap_quick_title": "Access Point (AP) Mode - Emergency Access",
    "ap_disabled_warning": "Warning: If AP Mode is disabled and WiFi is unavailable, device will be inaccessible! In such a case, you can reset to factory settings by holding the middle button for 20 seconds. You will need to restart the setup from the beginning.",
    "network_name": "Network Name (SSID)",
    "password": "Password",
    "no_password": "None (Open Network)",
    "ip_address_label": "IP Address",
    "mdns": "mDNS",
    "connection_order": "Connection Order",
    "step_primary": "1. Primary WiFi",
    "step_backup": "2. Backup WiFi",
    "step_ap": "3. AP Mode",
    "primary_wifi": "PRIMARY WIFI",
    "backup_wifi": "BACKUP WIFI",
    "not_configured": "Not Configured",
    "configured": "Configured",
    "connected": "Connected",
    "ssid_label": "SSID",
    "enter_ssid": "Enter WiFi SSID",
    "password_optional": "Password",
    "leave_empty_open": "Leave empty for open network",
    "open_network": "Leave empty for open network",
    "static_ip": "Static IP (optional)",
    "leave_empty_dhcp": "Leave empty for DHCP",
    "dhcp_hint": "Leave empty for DHCP",
    "local_domain": ".local Domain Name (configuration recommended)",
    "mdns_domain": ".local Domain (optional)",
    "mdns_example": "e.g.: dimm",
    "mdns_hint": "Will be accessible as [name].local on the network. If you have multiple SynDimm devices, you must assign a unique name to each one. Using the same name for multiple devices will cause network conflicts and the system will not work.",
    "save_network": "Save Network Configuration",
    "saving": "Saving settings...",
    "saved": "Settings saved! Restarting...",
    "save_failed": "Error: Could not save",
    "validation_ssid_long": "SSID max 32 characters",
    "validation_password": "Password must be 8-63 characters",
    "validation_ip": "Invalid Static IP",
    "validation_mdns": "mDNS max 63 characters",
    "validation_wifi_required": "At least one WiFi network required"
  },
  
  "info": {
    "version_update": "Version Update",
    "device_version": "Device Version:",
    "new_version": "New Version Available!",
    "new_version_available": "New Version Available!",
    "release_date": "Release Date:",
    "no_release_notes": "No release notes",
    "auto_update": "Automatic Update",
    "auto_update_info": "When automatic update is enabled, the device checks for new versions and updates itself. When disabled, you only receive notifications.",
    "auto_update_desc": "When automatic update is enabled, the device checks for new versions and updates itself. When disabled, you only receive notifications.",
    "check_update": "Check for Update",
    "update_now": "Update Now",
    "downloading": "Downloading...",
    "installing": "Installing...",
    "completed": "Completed!",
    "checking": "Checking for updates...",
    "update_found": "New version found!",
    "up_to_date": "Your device is up to date!",
    "update_starting": "Starting update...",
    "update_success": "Update successful! Restarting...",
    "update_failed": "Error: Update failed",
    "update_confirm": "Device will restart during update. Continue?",
    "usage_guide": "Usage Guide",
    "user_guide": "User Guide",
    "dimmer_mode": "Dimmer Mode",
    "dimmer_desc": "Works integrated with Shelly Dimmer devices. You can control lighting brightness with the encoder.",
    "dimmer_mode_title": "Dimmer Mode",
    "dimmer_mode_desc": "Works integrated with Shelly Dimmer devices. You can control lighting brightness with the encoder.",
    "encoder_rotation": "Encoder Rotation:",
    "dimmer_rotation_desc": "Turning right increases brightness, turning left decreases.",
    "encoder_rotation_dimmer": "Turning right increases brightness, turning left decreases.",
    "encoder_button": "Encoder Button:",
    "dimmer_button_desc": "Single press toggles the device on/off.",
    "encoder_button_dimmer": "Single press toggles the device on/off.",
    "calibration": "Calibration:",
    "dimmer_calibration_desc": "Calibration value between 1-5 can be set from web interface. This value determines the brightness percentage change for each encoder movement.",
    "calibration_title": "Calibration:",
    "calibration_dimmer": "Calibration value 1-5 can be set from web interface. This value determines the brightness percentage change for each encoder movement.",
    "device_connection": "Device Connection:",
    "dimmer_connection_desc": "Find and connect to Shelly Dimmer devices on your local network using the Scan Network button.",
    "device_connection_title": "Device Connection:",
    "device_connection_dimmer": "Find Shelly Dimmer devices on local network with Scan Network button and connect.",
    "shutter_mode": "Shutter Mode",
    "shutter_desc": "Works with shutter/blind controller devices like Shelly 2.5 or Shelly Plus 2PM.",
    "shutter_mode_title": "Shutter Mode",
    "shutter_mode_desc": "Works with shutter/blind controller devices like Shelly 2.5 or Shelly Plus 2PM.",
    "shutter_rotation_desc": "Turning right closes the shutter (down), turning left opens (up). Note: Encoder rotation is disabled if device is not calibrated.",
    "encoder_rotation_shutter": "Turning right closes the shutter (down), turning left opens (up). Note: If device is not calibrated, encoder rotation is disabled.",
    "shutter_button_desc": "Stops if moving. If stopped, performs full open or full close opposite to last movement.",
    "encoder_button_shutter": "Stops if moving. If stopped, does full open or full close in opposite direction of last movement.",
    "shutter_calibration_desc": "Motor calibration should be done from Shelly's own app. Encoder sensitivity (1-5) can be adjusted from web interface.",
    "calibration_shutter": "Motor calibration should be done from Shelly's own app. Encoder sensitivity (1-5) can be set from web interface.",
    "safe_mode": "Safe Mode",
    "safe_desc": "Password is entered with encoder movements and the defined API is called on correct password.",
    "safe_mode_title": "Safe Mode",
    "safe_mode_desc": "Password is entered with encoder movements and defined API is called on correct password.",
    "password_format_title": "Password Format:",
    "safe_format_desc": "Consists of movements like R5-L3-R2-B. R=right, L=left, number=rotation count, B=button.",
    "password_format_desc": "Consists of movements like R5-L3-R2-B. R=right, L=left, number=turns, B=button.",
    "settings": "Settings:",
    "safe_settings_desc": "5 different passwords can be defined from web interface. HTTP GET or POST API URL is entered for each password.",
    "safe_setup": "Setup:",
    "safe_setup_desc": "5 different passwords can be defined from web interface. HTTP GET or POST API URL is entered for each password.",
    "usage": "Usage:",
    "safe_usage_desc": "Suitable for smart lock opening, garage door control, custom automation scenarios.",
    "safe_usage": "Usage:",
    "alarm_mode": "Alarm Mode (Under Development)",
    "alarm_mode_title": "Alarm Mode (Under Development)",
    "emergency_notification": "Emergency Notification:",
    "alarm_notification_desc": "When you touch or turn the encoder (direction/amount doesn't matter), sends signal to mobile app via API.",
    "alarm_emergency": "Emergency Notification:",
    "alarm_emergency_desc": "When you touch or turn the encoder (direction/amount doesn't matter), sends signal to mobile app via API.",
    "function": "Function:",
    "alarm_function_desc": "Triggers ringtone on target phone and delivers emergency message.",
    "alarm_function": "Function:",
    "alarm_dev_note": "Alarm mode is under development.",
    "alarm_note": "Alarm mode is under development.",
    "general_features": "General Features",
    "mode_switch": "Mode Switch:",
    "mode_switch_desc": "Hold encoder button for 3 seconds. Enters preview mode, select mode by turning encoder, confirm by holding button for 3 seconds again.",
    "mode_switching": "Mode Switching:",
    "mode_switching_desc": "Hold encoder button for 3 seconds. Enters preview mode, select mode by turning encoder, confirm selection by holding button for 3 seconds again.",
    "wifi_connection": "WiFi Connection:",
    "wifi_desc": "Connect to WiFi network by entering SSID and password in Connection tab. DHCP or static IP options available. With mDNS support, you can also access via dimm.local address from browser.",
    "wifi_connection_desc": "Connect to WiFi network by entering SSID and password from Connection tab. DHCP or static IP options available. With mDNS support, you can also access via dimm.local address from browser.",
    "quick_menu": "Quick Menu:",
    "quick_menu_desc": "You can see active mode, WiFi status and IP address from status bar at top right. Clicking opens detailed system info panel.",
    "mode_memory": "Mode Memory:",
    "mode_memory_desc": "Selected mode is saved to flash memory and device automatically runs with last active mode when restarted.",
    "ota_update": "OTA Update:",
    "ota_desc": "New versions on GitHub can be checked from Info tab. If update available, wireless installation can be done with one click.",
    "ota_update_desc": "New versions on GitHub can be checked from Info tab. If update available, wireless installation can be done with one click.",
    "system_operations": "System Operations",
    "restart": "Restart",
    "factory_reset": "Factory Reset",
    "factory_reset_confirm": "All settings will be deleted. Type <strong>Yes</strong> to confirm:",
    "factory_reset_placeholder": "Yes",
    "confirm": "Confirm",
    "cancel": "Cancel",
    "factory_reset_validation": "You must type \"Yes\" to confirm!",
    "restarting": "Device is restarting...",
    "restart_success": "Device restarted. Page will refresh in 5 seconds.",
    "factory_resetting": "Factory reset in progress...",
    "factory_reset_success": "Factory reset completed. Device is restarting...",
    "support_docs": "Support and Documentation",
    "support_desc": "For detailed user guide, example scenarios and updates:"
  },
  
  "notifications": {
    "connection_error": "Connection error",
    "scanning": "Scanning network...",
    "scan_started": "Scan started",
    "scan_stopped": "Scan stopped",
    "scan_failed": "Scan could not be started",
    "scan_progress": "Scanning: {percent}% ({scanned}/{total}) - {count} devices",
    "scan_complete": "Completed! {count} devices found",
    "scan_complete_none": "Completed - no devices found",
    "setting_saved": "Setting saved",
    "setting_failed": "Could not save",
    "confirm_disconnect": "Are you sure you want to disconnect?",
    "confirm_remove": "Are you sure you want to remove this device?",
    "confirm_stop_scan": "Do you want to stop the scan?"
  },
  
  "common": {
    "save": "Save",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "close": "Close",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Info",
    "yes": "Yes",
    "no": "No",
    "on": "On",
    "off": "Off",
    "enabled": "Enabled",
    "disabled": "Disabled",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "increase": "Increase",
    "decrease": "Decrease",
    "passive": "Passive",
    "active": "Active",
    "automatic": "Automatic",
    "not_configured": "Not Configured",
    "note": "Note:"
  }
})rawliteral";

#endif // SK_LANG_EN_H
