/**
 * SK_lang_de.h
 * SmartKraft SynDimm - German Language Pack (Deutsch)
 * Version: v1.2.0
 */

#ifndef SK_LANG_DE_H
#define SK_LANG_DE_H

const char LANG_DE_JSON[] PROGMEM = R"rawliteral({
  "lang_code": "de",
  "lang_name": "Deutsch",
  
  "tabs": {
    "quick": "Schnellsteuerung",
    "modes": "Modi",
    "connection": "Verbindung",
    "info": "Info"
  },
  
  "quick": {
    "theme": "Design",
    "theme_dark": "Dunkel",
    "theme_light": "Hell",
    "language": "Sprache",
    "mode_config": "Modus-Konfiguration",
    "mode_selection": "Moduswahl",
    "connection_settings": "Verbindungseinstellungen",
    "device_settings": "Geräteeinstellungen",
    "wifi_settings": "WLAN-Einstellungen",
    "save_device_settings": "Geräteeinstellungen speichern",
    "settings_saved": "Geräteeinstellungen erfolgreich gespeichert"
  },
  
  "tooltip": {
    "dimmer_info": "Steuert die Shelly Dimmer Helligkeit mit Encoder-Drehung. Rechts erhöht, links verringert die Helligkeit.",
    "shutter_info": "Steuert Shelly Rolladen. Rechts schließt, links öffnet. Erfordert Gerätekalibrierung.",
    "safe_info": "Passwortgeschützter Modus. Definieren Sie Encoder-Sequenzen als Passwörter für API-Aufrufe.",
    "theme_hint": "Einstellung wird automatisch gespeichert.",
    "language_title": "Über Sprachen",
    "language_info": "Alle Oberflächentexte werden in die ausgewählte Sprache übersetzt. Die Einstellung wird automatisch gespeichert.",
    "mode_selection_info": "Wählen Sie den Betriebsmodus für den Encoder. Jeder Modus bietet unterschiedliche Funktionen.",
    "device_settings_info": "Konfigurieren Sie Design, Sprache und Netzwerkeinstellungen für Ihr Gerät.",
    "wifi_settings_info": "Konfigurieren Sie die primären und Backup-WLAN-Einstellungen, um Ihr Gerät mit dem Netzwerk zu verbinden. Sie können auch steuern, ob das Gerät über den Access Point (AP) Modus ein eigenes Netzwerk erstellt.",
    "version_info": "Suchen Sie nach Firmware-Updates über OTA (Over-the-Air).",
    "factory_reset_info": "Setzt alle Einstellungen auf Werksstandard zurück. Diese Aktion kann nicht rückgängig gemacht werden."
  },
  
  "modes": {
    "active": "Aktiv",
    "passive": "Passiv",
    "error": "Fehler"
  },
  
  "dimmer": {
    "title": "DIMMER",
    "description": "Steuern Sie Ihren Shelly Dimmer mit dem Encoder. Passen Sie die Helligkeit an und verwalten Sie Ein/Aus-Operationen.",
    "ip_address": "IP-ADRESSE",
    "status": "STATUS",
    "calibration": "KALIBRIERUNG",
    "action": "AKTION",
    "on": "An",
    "off": "Aus",
    "connect": "Verbinden",
    "disconnect": "Trennen",
    "device_connection": "Gerät verbinden",
    "manual_ip": "Manuelle IP-Eingabe",
    "scan_network": "Netzwerk scannen",
    "scan": "Scannen",
    "stop_scan": "Scan stoppen",
    "saved_devices": "Gespeicherte Geräte",
    "no_devices": "Noch keine gespeicherten Geräte. Scannen Sie das Netzwerk oder verbinden Sie manuell.",
    "no_saved_devices": "Keine gespeicherten Geräte. Scannen Sie das Netzwerk oder verbinden Sie manuell.",
    "found_devices": "Gefundene Geräte",
    "connecting": "Verbinde...",
    "connected": "Verbunden",
    "connection_failed": "Verbindung fehlgeschlagen",
    "disconnected": "Getrennt",
    "not_connected": "Nicht verbunden",
    "no_device_connected": "Kein Gerät verbunden",
    "sensitivity": "Empfindlichkeit",
    "enter_ip": "Bitte IP eingeben!",
    "invalid_ip": "Ungültige IP!",
    "calibration_saved": "Kalibrierung gespeichert!",
    "calibration_failed": "Kalibrierung konnte nicht gespeichert werden",
    "remove": "Entfernen",
    "device_removed": "Gerät entfernt",
    "remove_failed": "Entfernen fehlgeschlagen",
    "unknown": "Unbekannt",
    "shelly_dimmer": "Shelly Dimmer",
    "shelly_dali": "Shelly DALI",
    "tasmota": "Tasmota"
  },
  
  "shutter": {
    "title": "ROLLADEN",
    "description": "Steuern Sie Ihren Shelly Shutter mit dem Encoder. Passen Sie Vorhang- und Jalousiepositionen einfach an.",
    "ip_address": "IP-ADRESSE",
    "status": "STATUS",
    "position": "POSITION",
    "encoder_step": "ENCODER-SCHRITT",
    "connected": "Verbunden",
    "not_connected": "Nicht verbunden",
    "device_connection": "Geräteverbindung",
    "manual_ip": "Manuelle IP-Eingabe",
    "connect": "Verbinden",
    "disconnect": "Trennen",
    "scan_network": "Netzwerk scannen",
    "stop_scan": "Scan stoppen",
    "saved_devices": "Gespeicherte Geräte",
    "no_devices": "Noch keine gespeicherten Geräte. Scannen Sie das Netzwerk oder verbinden Sie manuell.",
    "no_saved_devices": "Keine gespeicherten Geräte. Scannen Sie das Netzwerk oder verbinden Sie manuell.",
    "connecting": "Verbinde...",
    "shutter_connected": "Rolladen verbunden!",
    "connection_failed": "Verbindung fehlgeschlagen",
    "disconnected": "Getrennt",
    "info_text": "Der Rolladen wird über den Encoder gesteuert. Sie können nur die Geschwindigkeitskalibrierung über Ihren Browser anpassen. Theoretisch vollständig, aber nicht an einem echten Rolladen getestet.",
    "calibration_warning": "Ihr Rolladengerät ist nicht kalibriert, Encoder-Drehung ist vorübergehend deaktiviert. Sie können jedoch weiterhin Vollständig öffnen, schließen und stoppen mit der Encoder-Taste ausführen.",
    "warning_encoder": "Der Rolladen wird über den Encoder gesteuert. Sie können nur die Geschwindigkeitskalibrierung über Ihren Browser anpassen. Theoretisch vollständig, aber nicht an einem echten Rolladen in der realen Welt getestet.",
    "warning_calibration": "Ihr Rolladengerät ist nicht kalibriert, daher sind die Encoder-Drehbewegungen vorübergehend deaktiviert. Sie können jedoch weiterhin die Funktionen Vollständig öffnen, Vollständig schließen und Stopp über die Encoder-Taste ausführen.",
    "shelly_shutter": "Shelly Rolladen",
    "stopped": "Gestoppt",
    "moving_up": "Nach oben",
    "moving_down": "Nach unten",
    "open": "Offen",
    "closed": "Geschlossen",
    "no_device_connected": "Kein Gerät verbunden"
  },
  
  "safe": {
    "title": "SAFE",
    "description": "Die Passworteingabe erfolgt über Encoder-Bewegungen. Sie können für jedes Passwort einen API-Endpunkt definieren. Wenn das richtige Passwort eingegeben wird, löst ESP32C6 automatisch die definierte API aus.",
    "password_1": "Passwort 1",
    "password_2": "Passwort 2",
    "password_3": "Passwort 3",
    "password_4": "Passwort 4",
    "password_5": "Passwort 5",
    "password_tab": "Passwort",
    "enable_password": "Passwort aktivieren",
    "password_label": "Passwort",
    "password": "Passwort",
    "password_format": "Format: L3-R12-L11-R3-B (Min: 3 Schritte, Max: 6 Schritte)",
    "api_url": "URL",
    "api_settings": "API-Einstellungen",
    "api_method": "Methode",
    "content_type": "Content-Type",
    "authorization": "Autorisierung",
    "custom_headers": "Benutzerdefinierte Header",
    "request_body": "Body (JSON)",
    "custom_header": "Benutzerdefinierter Header (optional)",
    "header_format": "Format: HeaderName: Wert",
    "save_password": "Speichern",
    "test_api": "API testen",
    "teach_password": "Lernen",
    "teaching_title": "Lernmodus",
    "teaching_hint": "Encoder drehen... Taste drücken zum Speichern",
    "cancel_teaching": "Abbrechen",
    "teaching_starting": "Lernmodus wird gestartet...",
    "teaching_started": "Lernmodus aktiv! Encoder drehen.",
    "teaching_cancelled": "Lernmodus abgebrochen",
    "teaching_timeout": "Lernzeit abgelaufen",
    "teaching_complete": "Passwort gelernt",
    "teaching_failed": "Lernmodus konnte nicht gestartet werden",
    "password_empty": "Passwort darf nicht leer sein!",
    "invalid_format": "Ungültiges Passwortformat! Beispiel: L3-R12-L11-R3-B",
    "api_empty": "API-URL darf nicht leer sein!",
    "saving": "Passwort wird gespeichert...",
    "saved": "Passwort erfolgreich gespeichert!",
    "save_failed": "Fehler: Konnte nicht gespeichert werden",
    "testing": "API wird getestet...",
    "test_success": "API-Test erfolgreich!",
    "test_failed": "API-Test fehlgeschlagen"
  },
  
  "alarm": {
    "title": "ALARM",
    "description": "Der Alarmmodus ist eine Sicherheitsfunktion, um Ihre Lieben sofort zu benachrichtigen oder in Notfällen Hilfe anzufordern. Wenn Sie mit dem Encoder interagieren, wird über die API ein Signal an die mobile App gesendet. Dieses Signal löst den Klingelton auf Telefonen mit der installierten App aus und zeigt Ihre vordefinierten Nachrichten auf dem Bildschirm an.",
    "example_title": "Beispiel-Anwendungsszenario:",
    "example_text": "Wenn sich Ihr SynDimm-Gerät im Alarmmodus befindet und Sie auf irgendeine Weise mit dem Encoder interagieren, wird automatisch eine Notfallanfrage an die mobile App auf Android- oder iOS-Geräten gesendet, die mit Ihrer Geräte-ID verknüpft sind. Telefone, die die Benachrichtigung erhalten, beginnen laut zu klingeln und Ihre vordefinierte Notfallnachricht wird auf dem Bildschirm angezeigt. Dies bietet eine intelligente Lösung, die Sie als Panikknopf für Ihre persönliche Sicherheit verwenden können.",
    "dev_note": "Das System befindet sich derzeit in der Entwicklung und wird in Kürze verfügbar sein.",
    "note": "Hinweis: Das System befindet sich derzeit in der Entwicklung und wird in Kürze verfügbar sein."
  },
  
  "connection": {
    "mode": "MODUS",
    "ssid": "SSID",
    "ip_address": "IP-ADRESSE",
    "ap_mode_title": "Access Point (AP) Modus",
"ap_mode_info": "Das Gerät erstellt bei der Ersteinrichtung automatisch ein eigenes Netzwerk. Es wird empfohlen, dies nach der WLAN-Konfiguration zu deaktivieren. Lassen Sie es aktiviert, wenn Sie ohne WLAN arbeiten möchten. Die unten stehenden Zugangsdaten sind fest und gelten immer, wenn der AP-Modus aktiv ist.",
    "ap_mode_description": "Bei fehlgeschlagener WLAN-Verbindung erstellt das Gerät sein eigenes Netzwerk. Verbinden Sie sich mit diesem Netzwerk, um auf die Einstellungen zuzugreifen.",
    "ap_mode_auto": "Automatisch",
    "ap_info": "Wenn keine WLAN-Verbindung hergestellt werden kann, öffnet das Gerät automatisch seinen eigenen Zugangspunkt. So können Sie das Gerät immer erreichen und konfigurieren.",
    "ap_mode_desc": "Wenn keine WLAN-Verbindung hergestellt werden kann, öffnet das Gerät automatisch seinen eigenen Zugangspunkt. So können Sie das Gerät immer erreichen und konfigurieren.",
    "wifi_connection_summary": "Gerät verbindet: Primäres WLAN → Backup-WLAN → Access Point (AP) Modus",
    "ap_quick_title": "Access Point (AP) Modus - Notfallzugriff",
    "ap_disabled_warning": "Warnung: Wenn der AP-Modus deaktiviert ist und WLAN nicht verfügbar ist, ist das Gerät nicht erreichbar! In einem solchen Fall können Sie durch 20-sekündiges Gedrückthalten der mittleren Taste auf die Werkseinstellungen zurücksetzen. Sie müssen die Einrichtung dann von vorne beginnen.",
    "network_name": "Netzwerkname (SSID)",
    "password": "Passwort",
    "no_password": "Keins (Offenes Netzwerk)",
    "ip_address_label": "IP-Adresse",
    "mdns": "mDNS",
    "connection_order": "Verbindungsreihenfolge",
    "step_primary": "1. Primäres WLAN",
    "step_backup": "2. Backup-WLAN",
    "step_ap": "3. AP-Modus",
    "primary_wifi": "PRIMÄRES WLAN",
    "backup_wifi": "BACKUP-WLAN",
    "not_configured": "Nicht konfiguriert",
    "configured": "Konfiguriert",
    "connected": "Verbunden",
    "ssid_label": "SSID",
    "enter_ssid": "WLAN-SSID eingeben",
    "password_optional": "Passwort",
    "leave_empty_open": "Für offenes Netzwerk leer lassen",
    "open_network": "Für offenes Netzwerk leer lassen",
    "static_ip": "Statische IP (optional)",
    "leave_empty_dhcp": "Für DHCP leer lassen",
    "dhcp_hint": "Für DHCP leer lassen",
    "local_domain": ".local-Domainname (Konfiguration empfohlen)",
    "mdns_domain": ".local-Domain (optional)",
    "mdns_example": "z.B.: dimm",
    "mdns_hint": "Wird als [name].local im Netzwerk erreichbar sein. Wenn Sie mehrere SynDimm-Geräte haben, müssen Sie jedem Gerät einen eindeutigen Namen zuweisen. Die Verwendung desselben Namens für mehrere Geräte führt zu Netzwerkkonflikten und das System funktioniert nicht.",
    "save_network": "Netzwerkkonfiguration speichern",
    "saving": "Einstellungen werden gespeichert...",
    "saved": "Einstellungen gespeichert! Neustart...",
    "save_failed": "Fehler: Konnte nicht gespeichert werden",
    "validation_ssid_long": "SSID max. 32 Zeichen",
    "validation_password": "Passwort muss 8-63 Zeichen haben",
    "validation_ip": "Ungültige statische IP",
    "validation_mdns": "mDNS max. 63 Zeichen",
    "validation_wifi_required": "Mindestens ein WLAN-Netzwerk erforderlich",
    "scan": "Scannen",
    "scan_wifi": "WLAN-Netzwerke scannen",
    "scanning": "Scannen...",
    "no_networks": "Keine Netzwerke gefunden",
    "rescan": "Erneut scannen",
    "wifi_open": "Offen",
    "wifi_secured": "Gesichert",
    "wifi_selected": "'{ssid}' ausgewählt"
  },
  
  "info": {
    "version_update": "Versionsupdate",
    "device_version": "Geräteversion:",
    "new_version": "Neue Version verfügbar!",
    "new_version_available": "Neue Version verfügbar!",
    "release_date": "Veröffentlichungsdatum:",
    "no_release_notes": "Keine Versionshinweise",
    "auto_update": "Automatisches Update",
    "auto_update_info": "Wenn das automatische Update aktiviert ist, prüft das Gerät auf neue Versionen und aktualisiert sich selbst. Wenn deaktiviert, erhalten Sie nur Benachrichtigungen.",
    "auto_update_desc": "Wenn das automatische Update aktiviert ist, prüft das Gerät auf neue Versionen und aktualisiert sich selbst. Wenn deaktiviert, erhalten Sie nur Benachrichtigungen.",
    "check_update": "Nach Update suchen",
    "update_now": "Jetzt aktualisieren",
    "downloading": "Wird heruntergeladen...",
    "installing": "Wird installiert...",
    "completed": "Abgeschlossen!",
    "checking": "Suche nach Updates...",
    "update_found": "Neue Version gefunden!",
    "up_to_date": "Ihr Gerät ist auf dem neuesten Stand!",
    "update_starting": "Update wird gestartet...",
    "update_success": "Update erfolgreich! Neustart...",
    "update_failed": "Fehler: Update fehlgeschlagen",
    "update_confirm": "Das Gerät wird während des Updates neu gestartet. Fortfahren?",
    "usage_guide": "Benutzerhandbuch",
    "user_guide": "Benutzerhandbuch",
    "dimmer_mode": "Dimmer-Modus",
    "dimmer_desc": "Funktioniert integriert mit Shelly Dimmer-Geräten. Sie können die Beleuchtungshelligkeit mit dem Encoder steuern.",
    "dimmer_mode_title": "Dimmer-Modus",
    "dimmer_mode_desc": "Funktioniert integriert mit Shelly Dimmer-Geräten. Sie können die Beleuchtungshelligkeit mit dem Encoder steuern.",
    "encoder_rotation": "Encoder-Drehung:",
    "dimmer_rotation_desc": "Nach rechts drehen erhöht die Helligkeit, nach links drehen verringert sie.",
    "encoder_rotation_dimmer": "Nach rechts drehen erhöht die Helligkeit, nach links drehen verringert sie.",
    "encoder_button": "Encoder-Taste:",
    "dimmer_button_desc": "Einmaliges Drücken schaltet das Gerät ein/aus.",
    "encoder_button_dimmer": "Einmaliges Drücken schaltet das Gerät ein/aus.",
    "calibration": "Kalibrierung:",
    "dimmer_calibration_desc": "Der Kalibrierungswert 1-5 kann über die Weboberfläche eingestellt werden. Dieser Wert bestimmt die Helligkeitsänderung in Prozent für jede Encoder-Bewegung.",
    "calibration_title": "Kalibrierung:",
    "calibration_dimmer": "Der Kalibrierungswert 1-5 kann über die Weboberfläche eingestellt werden. Dieser Wert bestimmt die Helligkeitsänderung in Prozent für jede Encoder-Bewegung.",
    "device_connection": "Geräteverbindung:",
    "dimmer_connection_desc": "Finden Sie Shelly Dimmer-Geräte im lokalen Netzwerk mit der Schaltfläche Netzwerk scannen und verbinden Sie sich.",
    "device_connection_title": "Geräteverbindung:",
    "device_connection_dimmer": "Finden Sie Shelly Dimmer-Geräte im lokalen Netzwerk mit der Schaltfläche Netzwerk scannen und verbinden Sie sich.",
    "shutter_mode": "Rolladen-Modus",
    "shutter_desc": "Funktioniert mit Rolladen-/Jalousiesteuerungsgeräten wie Shelly 2.5 oder Shelly Plus 2PM.",
    "shutter_mode_title": "Rolladen-Modus",
    "shutter_mode_desc": "Funktioniert mit Rolladen-/Jalousiesteuerungsgeräten wie Shelly 2.5 oder Shelly Plus 2PM.",
    "shutter_rotation_desc": "Nach rechts drehen schließt den Rolladen (runter), nach links drehen öffnet (hoch). Hinweis: Encoder-Drehung ist deaktiviert, wenn das Gerät nicht kalibriert ist.",
    "encoder_rotation_shutter": "Nach rechts drehen schließt den Rolladen (runter), nach links drehen öffnet (hoch). Hinweis: Wenn das Gerät nicht kalibriert ist, ist die Encoder-Drehung deaktiviert.",
    "shutter_button_desc": "Stoppt, wenn in Bewegung. Wenn gestoppt, führt vollständiges Öffnen oder Schließen in entgegengesetzter Richtung der letzten Bewegung aus.",
    "encoder_button_shutter": "Stoppt, wenn in Bewegung. Wenn gestoppt, führt vollständiges Öffnen oder Schließen in entgegengesetzter Richtung der letzten Bewegung aus.",
    "shutter_calibration_desc": "Die Motorkalibrierung sollte über die Shelly-App erfolgen. Die Encoder-Empfindlichkeit (1-5) kann über die Weboberfläche eingestellt werden.",
    "calibration_shutter": "Die Motorkalibrierung sollte über die Shelly-App erfolgen. Die Encoder-Empfindlichkeit (1-5) kann über die Weboberfläche eingestellt werden.",
    "safe_mode": "Safe-Modus",
    "safe_desc": "Das Passwort wird mit Encoder-Bewegungen eingegeben und bei korrektem Passwort wird die definierte API aufgerufen.",
    "safe_mode_title": "Safe-Modus",
    "safe_mode_desc": "Das Passwort wird mit Encoder-Bewegungen eingegeben und bei korrektem Passwort wird die definierte API aufgerufen.",
    "password_format_title": "Passwortformat:",
    "safe_format_desc": "Besteht aus Bewegungen wie R5-L3-R2-B. R=rechts, L=links, Zahl=Drehungen, B=Taste.",
    "password_format_desc": "Besteht aus Bewegungen wie R5-L3-R2-B. R=rechts, L=links, Zahl=Umdrehungen, B=Taste.",
    "settings": "Einstellungen:",
    "safe_settings_desc": "5 verschiedene Passwörter können über die Weboberfläche definiert werden. Für jedes Passwort wird eine HTTP GET- oder POST-API-URL eingegeben.",
    "safe_setup": "Einrichtung:",
    "safe_setup_desc": "5 verschiedene Passwörter können über die Weboberfläche definiert werden. Für jedes Passwort wird eine HTTP GET- oder POST-API-URL eingegeben.",
    "usage": "Verwendung:",
    "safe_usage_desc": "Geeignet für Smart-Lock-Öffnung, Garagentorsteuerung, benutzerdefinierte Automatisierungsszenarien.",
    "safe_usage": "Verwendung:",
    "alarm_mode": "Alarm-Modus (In Entwicklung)",
    "alarm_mode_title": "Alarm-Modus (In Entwicklung)",
    "emergency_notification": "Notfallbenachrichtigung:",
    "alarm_notification_desc": "Wenn Sie den Encoder berühren oder drehen (Richtung/Menge spielt keine Rolle), wird ein Signal über die API an die mobile App gesendet.",
    "alarm_emergency": "Notfallbenachrichtigung:",
    "alarm_emergency_desc": "Wenn Sie den Encoder berühren oder drehen (Richtung/Menge spielt keine Rolle), wird ein Signal über die API an die mobile App gesendet.",
    "function": "Funktion:",
    "alarm_function_desc": "Der Klingelton wird auf dem Zieltelefon ausgelöst und die Notfallnachricht wird übermittelt.",
    "alarm_function": "Funktion:",
    "alarm_dev_note": "Der Alarm-Modus befindet sich in der Entwicklung.",
    "alarm_note": "Der Alarm-Modus befindet sich in der Entwicklung.",
    "general_features": "Allgemeine Funktionen",
    "mode_switch": "Moduswechsel:",
    "mode_switch_desc": "Halten Sie die Encoder-Taste 3 Sekunden gedrückt. Wechselt in den Vorschaumodus, wählen Sie den Modus durch Drehen des Encoders, bestätigen Sie durch erneutes 3-sekündiges Drücken.",
    "mode_switching": "Moduswechsel:",
    "mode_switching_desc": "Halten Sie die Encoder-Taste 3 Sekunden gedrückt. Wechselt in den Vorschaumodus, wählen Sie den Modus durch Drehen des Encoders, bestätigen Sie die Auswahl durch erneutes 3-sekündiges Drücken der Taste.",
    "wifi_connection": "WLAN-Verbindung:",
    "wifi_desc": "Verbinden Sie sich mit dem WLAN-Netzwerk, indem Sie SSID und Passwort auf der Verbindungsseite eingeben. DHCP- oder statische IP-Optionen verfügbar. Mit mDNS-Unterstützung können Sie auch über dimm.local-Adresse im Browser zugreifen.",
    "wifi_connection_desc": "Verbinden Sie sich mit dem WLAN-Netzwerk, indem Sie SSID und Passwort auf der Verbindungsseite eingeben. DHCP- oder statische IP-Optionen verfügbar. Mit mDNS-Unterstützung können Sie auch über die dimm.local-Adresse im Browser zugreifen.",
    "quick_menu": "Schnellmenü:",
    "quick_menu_desc": "Sie können den aktiven Modus, den WLAN-Status und die IP-Adresse in der Statusleiste oben rechts sehen. Durch Klicken öffnet sich das detaillierte Systeminfo-Panel.",
    "mode_memory": "Modus-Speicher:",
    "mode_memory_desc": "Der ausgewählte Modus wird im Flash-Speicher gespeichert und das Gerät arbeitet beim Neustart automatisch mit dem zuletzt aktiven Modus.",
    "ota_update": "OTA-Update:",
    "ota_desc": "Neue Versionen auf GitHub können auf der Info-Seite überprüft werden. Wenn ein Update verfügbar ist, kann mit einem Klick eine drahtlose Installation durchgeführt werden.",
    "ota_update_desc": "Neue Versionen auf GitHub können auf der Info-Seite überprüft werden. Wenn ein Update verfügbar ist, kann mit einem Klick eine drahtlose Installation durchgeführt werden.",
    "system_operations": "Systemoperationen",
    "restart": "Neustart",
    "factory_reset": "Werksreset",
    "factory_reset_confirm": "Alle Einstellungen werden gelöscht. Geben Sie <strong>Ja</strong> zur Bestätigung ein:",
    "factory_reset_placeholder": "Ja",
    "confirm": "Bestätigen",
    "cancel": "Abbrechen",
    "factory_reset_validation": "Sie müssen \"Ja\" eingeben, um zu bestätigen!",
    "restarting": "Gerät wird neu gestartet...",
    "restart_success": "Gerät neu gestartet. Seite wird in 5 Sekunden aktualisiert.",
    "factory_resetting": "Werksreset wird durchgeführt...",
    "factory_reset_success": "Werksreset abgeschlossen. Gerät wird neu gestartet...",
    "support_docs": "Support und Dokumentation",
    "support_desc": "Für detailliertes Benutzerhandbuch, Beispielszenarien und Updates:"
  },
  
  "notifications": {
    "connection_error": "Verbindungsfehler",
    "scanning": "Netzwerk wird gescannt...",
    "scan_started": "Scan gestartet",
    "scan_stopped": "Scan gestoppt",
    "scan_failed": "Scan konnte nicht gestartet werden",
    "scan_progress": "Scannen: {percent}% ({scanned}/{total}) - {count} Geräte",
    "scan_complete": "Abgeschlossen! {count} Geräte gefunden",
    "scan_complete_none": "Abgeschlossen - keine Geräte gefunden",
    "setting_saved": "Einstellung gespeichert",
    "setting_failed": "Konnte nicht gespeichert werden",
    "confirm_disconnect": "Sind Sie sicher, dass Sie die Verbindung trennen möchten?",
    "confirm_remove": "Sind Sie sicher, dass Sie dieses Gerät entfernen möchten?",
    "confirm_stop_scan": "Möchten Sie den Scan stoppen?"
  },
  
  "common": {
    "save": "Speichern",
    "cancel": "Abbrechen",
    "confirm": "Bestätigen",
    "close": "Schließen",
    "loading": "Laden...",
    "error": "Fehler",
    "success": "Erfolg",
    "warning": "Warnung",
    "info": "Info",
    "yes": "Ja",
    "no": "Nein",
    "on": "An",
    "off": "Aus",
    "enabled": "Aktiviert",
    "disabled": "Deaktiviert",
    "connect": "Verbinden",
    "disconnect": "Trennen",
    "increase": "Erhöhen",
    "decrease": "Verringern",
    "passive": "Passiv",
    "active": "Aktiv",
    "automatic": "Automatisch",
    "not_configured": "Nicht konfiguriert",
    "note": "Hinweis:"
  }
})rawliteral";

#endif // SK_LANG_DE_H
